language: python
addons:
  apt:
    packages:
    - autoconf
    - check
    - g++
    - libtool
    - libsubunit-dev
    - pkg-config
    - python3-dev
    - python3-setuptools
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
  - "autoreconf -i"
  - "./configure"
script: "make check"
