language: python
addons:
  apt:
    packages:
    - autoconf
    - check
    - g++
    - libtool
    - libsubunit-dev
    - pkg-config
    - python3-dev
    - python3-setuptools
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
script:
  - autoreconf -i && ./configure --enable-maintainer-mode CFLAGS='-O0 --coverage' && make && make check
after_success:
  - bash <(curl -s https://codecov.io/bash) 