name: gubbins_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python>=3.8
  - autoconf
  - check
  - g++
  - libtool
  - libsubunit-dev
  - pkg-config
  - python3-dev
  - python3-setuptools
  - raxml
  - iqtree
  - rapidnj
  - raxml-ng
  - fasttree
