name: gubbins_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python>=3.8
  - autoconf
  - check
  - libtool
  - pkg-config
  - wheel
  - raxml
  - iqtree
  - rapidnj
  - raxml-ng
  - fasttree
