name: gubbins_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - autoconf
  - check
  - g++
  - libtool
  - libsubunit-dev
  - pkg-config
  - python3-dev
  - python3-setuptools
