name: gubbins_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
# python
  - python>=3.8
# installation
  - autoconf
  - automake
  - pytest
  - check
  - libtool
  - libevent
  - gettext
  - cppunit
  - openssl
  - boost
  - gettext
  - pkg-config
  - wheel
  - nose
  - pillow
# algorithm
  - scipy
  - dendropy
  - biopython
  - multiprocess
# phylogenetics
  - raxml
  - iqtree
  - rapidnj
  - raxml-ng
  - fasttree
