name: gubbins_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python>=3.8
  - autoconf
  - automake
  - pytest
  - check
  - libtool
  - libevent
  - gettext
  - cppunit
  - openssl
  - boost
  - gettext
  - pkg-config
  - wheel
  - scipy
  - dendropy
  - raxml
  - iqtree
  - rapidnj
  - raxml-ng
  - fasttree
  - wheel
  - nose
  - pillow
  - dendropy
  - biopython
  - functools
  - multiprocess
